/**
 * Database migration script.
 *
 * Usage: pnpm db:migrate
 *
 * This script reads migration SQL files generated by drizzle-kit
 * and executes them against the database.
 *
 * Prerequisite: run `pnpm db:generate` first to generate migration files.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import pg from 'pg';
import config from '../config.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const migrationsDir = path.join(__dirname, 'migrations');
const { Pool } = pg;

async function migrate() {
  if (!config.DATABASE_URL) {
    console.error('[Migrate] DATABASE_URL is not set. Cannot run migrations.');
    process.exit(1);
  }

  const sslConfig =
    config.DB_SSL === 'false'
      ? false
      : { rejectUnauthorized: config.NODE_ENV === 'production' };

  const pool = new Pool({
    connectionString: config.DATABASE_URL,
    ssl: sslConfig,
  });

  const client = await pool.connect();

  try {
    // Ensure drizzle migrations tracking table exists
    await client.query(`
      CREATE TABLE IF NOT EXISTS __drizzle_migrations (
        id SERIAL PRIMARY KEY,
        hash TEXT NOT NULL,
        created_at TIMESTAMP DEFAULT NOW()
      );
    `);

    // Read migration files
    if (!fs.existsSync(migrationsDir)) {
      console.log('[Migrate] No migrations directory found. Run `pnpm db:generate` first.');
      return;
    }

    const files = fs
      .readdirSync(migrationsDir)
      .filter((f) => f.endsWith('.sql'))
      .sort();

    if (files.length === 0) {
      console.log('[Migrate] No migration files found.');
      return;
    }

    for (const file of files) {
      const filePath = path.join(migrationsDir, file);
      const sql = fs.readFileSync(filePath, 'utf8');

      // Check if migration was already applied
      const { rows } = await client.query(
        'SELECT 1 FROM __drizzle_migrations WHERE hash = $1',
        [file]
      );

      if (rows.length > 0) {
        console.log(`[Migrate] Skipping already applied: ${file}`);
        continue;
      }

      console.log(`[Migrate] Applying: ${file}`);
      await client.query(sql);
      await client.query(
        'INSERT INTO __drizzle_migrations (hash) VALUES ($1)',
        [file]
      );
      console.log(`[Migrate] Applied: ${file}`);
    }

    console.log('[Migrate] All migrations applied successfully.');
  } catch (err) {
    console.error('[Migrate] Migration failed:', err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

migrate();
