# ───────────────────────────────────────────────────────────────────
# Nginx Reverse Proxy
# ───────────────────────────────────────────────────────────────────
FROM nginx:alpine AS nginx-proxy

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
